# Generated by Django 4.2 on 2024-04-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='other_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ClubPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(blank=True)),
                ('total_point', models.PositiveIntegerField(blank=True)),
                ('ground', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], max_length=50)),
                ('outcome', models.CharField(choices=[('Win', 'Win'), ('Draw', 'Draw'), ('Lose', 'Lose')], max_length=10)),
                ('matchweek', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38)])),
                ('goals_scored', models.PositiveIntegerField(blank=True)),
                ('goals_against', models.PositiveIntegerField(blank=True)),
                ('club', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Club', to='app.team')),
                ('club_against', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Club_against', to='app.team')),
                ('season', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.season')),
                ('tournament', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tournament')),
            ],
        ),
    ]
