# Generated by Django 4.2 on 2024-05-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpoint',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubpoint',
            name='ground',
            field=models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Neutral', 'Neutral')], max_length=50),
        ),
    ]
