# Generated by Django 4.2 on 2024-05-08 23:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_clubpoint_date_alter_clubpoint_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
