# Generated by Django 4.2.3 on 2024-05-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_season_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['name', 'year']},
        ),
    ]
