# Generated by Django 4.2.3 on 2024-05-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_birthyear_playernationality_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.AlterField(
            model_name='playerrecord',
            name='starts',
            field=models.PositiveIntegerField(help_text='Total number of matches started'),
        ),
    ]
