# Generated by Django 4.2.3 on 2024-05-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_playernationality_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playernationality',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='playernationality',
            name='country_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
