# Generated by Django 4.2.3 on 2024-05-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_player_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthyear',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='clubpoint',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='playerrecord',
            options={'ordering': ['-goals']},
        ),
        migrations.AlterField(
            model_name='clubpoint',
            name='tournament',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_tournament', to='app.tournament'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament', to='app.tournament'),
        ),
    ]
