# Generated by Django 4.2.3 on 2024-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_customerpayment_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
