# Generated by Django 4.2 on 2024-04-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player')),
            ],
        ),
        migrations.CreateModel(
            name='OtherStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.PositiveIntegerField()),
                ('time', models.TimeField()),
                ('player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.playerstat')),
                ('tournament', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='GoalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('goal_scored', models.PositiveIntegerField()),
                ('player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.playerstat')),
                ('tournament', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='AssitStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('assit_made', models.PositiveIntegerField()),
                ('player', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.playerstat')),
                ('tournament', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tournament')),
            ],
        ),
    ]
