# Generated by Django 4.2.3 on 2024-07-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WordBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='anagram.letter')),
            ],
        ),
    ]
