# Generated by Django 4.2.3 on 2024-08-06 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbuilding',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_letter', to='anagram.letter'),
        ),
    ]
