# Generated by Django 4.2.3 on 2024-08-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0002_alter_wordbuilding_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='creatd_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
