# Generated by Django 4.2.3 on 2024-08-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0003_letter_creatd_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='creatd_at',
            new_name='created_at',
        ),
    ]
