# Generated by Django 4.2.3 on 2024-08-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0004_rename_creatd_at_letter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
